=== MartinMZan/N16IAF_XMLGyak/XMLTaskN16IAF/DOMParseN16IAF/src/XMLSchemaN16IAF.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- Gyokerelem -->
	<xs:element name="bank">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="cim" type="cim_tipus"/>
			<xs:element name="ugyfel" type="ugyfel_tipus" maxOccurs="unbounded"/>
			<xs:element name="banki_alkalmazott" type="banki_alkalmazott_tipus" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="cegnev" type="xs:string" use="required"/>
		</xs:complexType>
		
		<!-- Kulcsok -->
		<xs:key name="cegnev">
            <xs:selector xpath="bank"/>
            <xs:field xpath="@cegnev"/>
        </xs:key>
		
		<xs:key name="ugyfel_azonosito">
            <xs:selector xpath="ugyfel"/>
            <xs:field xpath="@ugyfel_azonosito"/>
        </xs:key>
        
        <xs:key name="alkalmazott_azonosito">
            <xs:selector xpath="banki_alkalmazott"/>
            <xs:field xpath="@alkalmazott_azonosito"/>
        </xs:key>
        
        <xs:key name="bankszamla_szam">
            <xs:selector xpath="bankszamla"/>
            <xs:field xpath="@bankszamla_szam"/>
        </xs:key>
        
        <xs:key name="bankkartya_szam">
            <xs:selector xpath="bankkartya"/>
            <xs:field xpath="@bankkartya_szam"/>
        </xs:key>
        
	</xs:element>    


	<!-- Egyszeru tipusok -->
	<xs:simpleType name="penznem_tipus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="HUF"/>
			<xs:enumeration value="EUR"/>
			<xs:enumeration value="GBP"/>
			<xs:enumeration value="CHF"/>
			<xs:enumeration value="USD"/>
			<xs:enumeration value="KRW"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="cvc_kod_tipus">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="100"/>
			<xs:maxInclusive value="999"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	<!-- Komplex tipusok -->
	<xs:complexType name="cim_tipus">
		<xs:sequence>
			<xs:element name="varos" type="xs:string"/>
			<xs:element name="utca" type="xs:string"/>
			<xs:element name="hazszam" type="xs:unsignedInt"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ugyfel_tipus">
		<xs:sequence>
			<xs:element name="cim" type="cim_tipus"/>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="bank" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ugyfel_azonosito" type="xs:int" use="required"/>
	</xs:complexType>

	<xs:complexType name="banki_alkalmazott_tipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="szuletesi_ev" type="xs:gYear"/>
			<xs:element name="bankszamla" type="bankszamla_tipus" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="alkalmazott_azonosito" type="xs:int" use="required"/>
	</xs:complexType>

	<xs:complexType name="bankszamla_tipus">
		<xs:sequence>
			<xs:element name="egyenleg" type="xs:int"/>
			<xs:element name="penznem" type="penznem_tipus"/>
			<xs:element name="korabbi_tranzakciok" type="xs:int" minOccurs="0" maxOccurs="30"/>
			<xs:element name="bankkartya" type="bankkartya_tipus" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="bankszamla_szam" type="xs:decimal" use="required"/> <!-- Itt csak azert szukseges decimal, mert az int-be nem fer bele -->
	</xs:complexType>
	
	<xs:complexType name="bankkartya_tipus">
		<xs:sequence>
			<xs:element name="lejarati_datum" type="xs:date"/>
			<xs:element name="cvckod" type="cvc_kod_tipus"/>
			<xs:element name="ketkulcsos_azonosito" type="xs:int" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="bankkartya_szam" type="xs:decimal" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== MartinMZan/N16IAF_XMLGyak/XMLTaskN16IAF/XMLN16IAF.xml
<?xml version="1.0" encoding="utf-8"?>

<bank cegnev="OTP" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaN16IAF.xsd">
	<cim>
		<varos>Miskolc</varos>
		<utca>Uitz Béla</utca>
		<hazszam>6</hazszam>
	</cim>
	
	<ugyfel ugyfel_azonosito="1">
		<cim>
			<varos>Ózd</varos>
			<utca>József Attila</utca>
			<hazszam>215</hazszam>
		</cim>
		<nev>Kulcsár Ádám</nev>
		<bank>OTP</bank>
	</ugyfel>

	<ugyfel ugyfel_azonosito="2">
		<cim>
			<varos>Miskolc</varos>
			<utca>Vörösmarty Mihály</utca>
			<hazszam>454</hazszam>
		</cim>
		<nev>Szabó Henrietta</nev>
		<bank>OTP</bank>
		<bank>ERSTE</bank>
	</ugyfel>

	<banki_alkalmazott alkalmazott_azonosito="1">
		<nev>Visegrádi Iván</nev>
		<szuletesi_ev>1988</szuletesi_ev>
		
		<bankszamla bankszamla_szam="1343598542375482">
			<egyenleg>540</egyenleg>
			<penznem>EUR</penznem>
			<korabbi_tranzakciok>-400</korabbi_tranzakciok>
			<korabbi_tranzakciok>200</korabbi_tranzakciok>
			
			<bankkartya bankkartya_szam="5012443244328394">
				<lejarati_datum>2022-08-30</lejarati_datum>
				<cvckod>632</cvckod>
				<ketkulcsos_azonosito>7892</ketkulcsos_azonosito>
			</bankkartya>
			
		</bankszamla>
		
	</banki_alkalmazott>
	
	<banki_alkalmazott alkalmazott_azonosito="2">
		<nev>Galambos Lajos</nev>
		<szuletesi_ev>1965</szuletesi_ev>
		
		<bankszamla bankszamla_szam="1343698541375482">
			<egyenleg>2200000</egyenleg>
			<penznem>KRW</penznem>
			
			<bankkartya bankkartya_szam="1912443244328394">
				<lejarati_datum>2024-11-21</lejarati_datum>
				<cvckod>112</cvckod>
				<ketkulcsos_azonosito>1234</ketkulcsos_azonosito>
			</bankkartya>
			
		</bankszamla>

		<bankszamla bankszamla_szam="1343498344375482">
			<egyenleg>-54</egyenleg>
			<penznem>HUF</penznem>
			<korabbi_tranzakciok>-54</korabbi_tranzakciok>
			
			<bankkartya bankkartya_szam="1612475254308394">
				<lejarati_datum>2019-11-21</lejarati_datum>
				<cvckod>748</cvckod>
			</bankkartya>

		</bankszamla>
		
	</banki_alkalmazott>
</bank>
