=== MartinMZan/N16IAF_XMLGyak/N16IAF_1021/ZMM_orarend1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    targetNamespace="http://www.w3schools.com/ZMM_orarend1"
    elementFormDefault="qualified"
    xmlns="http://www.w3schools.com/ZMM_orarend1.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

	<xs:element name="orarend">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="hetfo" type="naptipus"></xs:element>
				<xs:element name="kedd" type="naptipus"></xs:element>
				<xs:element name="szerda" type="naptipus"></xs:element>
				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="naptipus">
						<xs:sequence>
						<xs:element name="ora" maxOccurs="unbounded" type="oratipus">
						</xs:element>
						</xs:sequence>
	</xs:complexType>

	<xs:complexType name="oratipus">
								<xs:sequence>
									<xs:element name="targy" type="xs:string" />
									<xs:element name="idopont">
										<xs:complexType>
											<xs:sequence>
											<xs:element name="nap" type="xs:string" />
											<xs:element name="tol" type="xs:int" />
											<xs:element name="ig" type="xs:int"/>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="helyszin" type="xs:string"/>
									<xs:element name="oktato" type="xs:string"/>
									<xs:element name="szak" type="xs:string"/>
								</xs:sequence>
								<xs:attribute name="id" type="xs:string"/>
								<xs:attribute name="tipus" type="xs:string"/>
	</xs:complexType>


	
</xs:schema>

=== MartinMZan/N16IAF_XMLGyak/N16IAF_1012/ZMM_orarend1.xml
<?xml version="1.0" encoding="utf-8"?>



<orarend xmlns="http://www.w3schools.com/ZMM_orarend1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.w3schools.com/ZMM_orarend1.xsd"
>
	<hetfo>
		
		<ora id="a" tipus="eloadas es gyakorlat">
			<targy>Algoritmusok es vizsgalatuk</targy>
			<idopont>
				<nap>hetfo</nap>
				<tol>8</tol>
				<ig>12</ig>
			</idopont>
			<helyszin>A3. 313.</helyszin>
			<oktato>Dr. Hazy Attila</oktato>
			<szak>PTI</szak>
		</ora>
		<ora id="b" tipus="eloadas">
			<targy>Web technologiak</targy>
			<idopont>
				<nap>hetfo</nap>
				<tol>12</tol>
				<ig>14</ig>
			</idopont>
			<helyszin>A1. 305.</helyszin>
			<oktato>Agardi Anita</oktato>
			<szak>PTI</szak>
		</ora>
		<ora id="c" tipus="eloadas">
			<targy>Mesterseges intelligencia</targy>
			<idopont>
				<nap>hetfo</nap>
				<tol>14</tol>
				<ig>17</ig>
			</idopont>
			<helyszin>A1. magasfsz. XXXII.</helyszin>
			<oktato>Dr. Dudas Laszlo</oktato>
			<szak>PTI</szak>
		</ora>
		
	</hetfo>

	<kedd>

		<ora id="d" tipus="eloadas">
			<targy>Adatkezeles XML-ben</targy>
			<idopont>
				<nap>kedd</nap>
				<tol>12</tol>
				<ig>14</ig>
			</idopont>
			<helyszin>A2. fsz. I.</helyszin>
			<oktato>Dr. Bednarik Laszlo</oktato>
			<szak>PTI</szak>
		</ora>

		<ora id="e" tipus="gyakorlat">
			<targy>Adatkezeles XML-ben</targy>
			<idopont>
				<nap>kedd</nap>
				<tol>14</tol>
				<ig>16</ig>
			</idopont>
			<helyszin>Info. 103.</helyszin>
			<oktato>Dr. Bednarik Laszlo</oktato>
			<szak>PTI</szak>
		</ora>

		<ora id="f" tipus="gyakorlat">
			<targy>Web technologiak</targy>
			<idopont>
				<nap>kedd</nap>
				<tol>16</tol>
				<ig>18</ig>
			</idopont>
			<helyszin>Info. 103.</helyszin>
			<oktato>Agardi Anita</oktato>
			<szak>PTI</szak>
		</ora>
		
	</kedd>

	<szerda>

		<ora id="g" tipus="gyakorlat">
			<targy>Mesterseges intelligencia</targy>
			<idopont>
				<nap>szerda</nap>
				<tol>13</tol>
				<ig>14</ig>
			</idopont>
			<helyszin>Info. 15.</helyszin>
			<oktato>Dr. Dudas Laszlo</oktato>
			<szak>PTI</szak>
		</ora>

		<ora id="h" tipus="eloadas es gyakorlat">
			<targy>Vallalati informacios rendszerek fejlesztese</targy>
			<idopont>
				<nap>szerda</nap>
				<tol>16</tol>
				<ig>20</ig>
			</idopont>
			<helyszin>Info. 103.</helyszin>
			<oktato>Dr. Sasvari Peter Laszlo</oktato>
			<szak>PTI</szak>
		</ora>

	</szerda>
</orarend>
